import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  chatButton: {
    position: "absolute",
    bottom: 24,
    right: 24,
    backgroundColor: "#007bff",
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 8,
    zIndex: 1000,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "flex-end",
  },
  chatContainer: {
    width: "100%",
    height: "92%",
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: "hidden",
  },
  header: {
    backgroundColor: "#007bff",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  headerTitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerText: {
    color: "white",
    fontWeight: "600",
    fontSize: 16,
    marginLeft: 8,
  },
  messages: {
    flex: 1,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: "#f0f2f5",
  },
  messageContainer: {
    marginBottom: 15,
    flexDirection: "row",
  },
  messageLeft: {
    justifyContent: "flex-start",
  },
  messageRight: {
    justifyContent: "flex-end",
  },
  messageBubble: {
    maxWidth: "73%",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
  },
  userBubble: {
    backgroundColor: "#007bff",
  },
  botBubble: {
    backgroundColor: "#e4e6eb",
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
  },

  avatarBot: {
    width: 30,
    height: 30,
    borderRadius: 16,
    backgroundColor: "#e0e0e0",
    paddingLeft: 8.3,
    paddingTop: 5,
    marginRight: 8,
    justifyContent: "center",
    alignSelf: "flex-end",
  },
  avatarUser: {
    width: 30,
    height: 30,
    borderRadius: 16,
    backgroundColor: "#007bff",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 9.8,
    paddingTop: 7,
    marginLeft: 8,
    alignSelf: "flex-end",
  },
  userText: {
    color: "#fff",
  },
  botText: {
    color: "#000",
  },
  inputArea: {
    flexDirection: "row",
    padding: 10,
    borderTopWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#fff",
    alignItems: "center",
  },
  textInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 20,
    paddingHorizontal: 16,
    height: 42,
    backgroundColor: "#fff",
    fontSize: 14,
  },
  sendButton: {
    backgroundColor: "#007bff",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  sendText: {
    color: "white",
    fontWeight: "600",
    fontSize: 14,
  },
});
``;
