name: Build and Deploy ADNTester API

on:
  push:
    branches:
      - be-main  # Adjust if needed

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
           docker build -f BE/ADNTester/ADNTester.Api/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/adntester:latest ./BE/ADNTester

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/adntester:latest

  deploy:
    name: Deploy adntester.api Service
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.ADN_SERVER_IP }}
          username: ${{ secrets.ADN_SERVER_USER }}
          key: ${{ secrets.ADN_SERVER_SSH_KEY }}
          script: |
            echo "→ Navigating to project directory"
            cd ~/adntester

            echo "→ Pulling latest image for adntester.api"
            docker compose pull adntester.api

            echo "→ Rebuilding and restarting adntester.api only"
            docker compose up -d --no-deps --build adntester.api

            echo "API service deployed successfully"
